openapi: 3.0.0
info:
  title: Jobs API
  version: 1.0.0
  description: API for user authentication and job management.

servers:
  - url: https://jobs-api-wtzq.onrender.com/api/v1
  - url: http://localhost:3000/api/v1

tags:
  - name: Auth
    description: User authentication routes
  - name: Jobs
    description: Job CRUD operations

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [name, email, password]
      responses:
        '201':
          description: User registered successfully

  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      servers:
        - url: https://jobs-api-wtzq.onrender.com/api/v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Login successful

  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                position:
                  type: string
              required: [company, position]
      responses:
        '201':
          description: Job created successfully

    get:
      tags:
        - Jobs
      summary: Get All Jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of jobs

  /jobs/{jobId}:
    get:
      tags:
        - Jobs
      summary: Get Job By Id
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job details returned

    patch:
      tags:
        - Jobs
      summary: Update Job
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                position:
                  type: string
      responses:
        '200':
          description: Job updated successfully

    delete:
      tags:
        - Jobs
      summary: Delete Job By Id
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job deleted successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
